ConflictException.message={0}({1}) already exists
NotFoundException.message={0}({1}) was not found
